### ISSUE TITLE
Packaging in Conda

### ISSUE THREAD

**Issue by lecorguille** [Rosemeis/pcangsd#79]
Dear @Rosemeis,

Can you consider to package pcangsd in [Bioconda](bioconda.github.io/)?

Conda (through Bioconda) is the solution for the FAIRness of your tool.
I could have done it myself but I lake some spare time curently. But I can help you if needed, let me know!
BTW, you will see that it's really simple regarding the few dependencies of pcangsd.

**Comment by lecorguille** [comment]
Oh, and https://bio.tools/ is worth to consider to :)

**Comment by pdimens** [comment]
I second this. Can help create recipe on bioconda if needed

**Comment by pdimens** [comment]
The recipe would look something like:
```yaml
{% set version = "" %}
{% set sha256 = "" %}

package:
  name: pcangsd
  version: '{{ version }}'

source:
  url:  https://github.com/Rosemeis/pcangsd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pcangsd', max_pin="x.x") }}
  script: ${PYTHON} -m pip install . --no-deps -vvv
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - cython

test:
  commands:
    - "pcangsd -h"

about:
  home: "https://github.com/Rosemeis/pcangsd/"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "Framework for analyzing low-depth next-generation sequencing (NGS) data in heterogeneous/structured populations using principal component analysis (PCA)."
  doc_url: https://github.com/Rosemeis/pcangsd/
  dev_url: https://github.com/Rosemeis/pcangsd/

extra:
  recipe-maintainers:
    - Rosemeis
```
